<a href="https://colab.research.google.com/github/Jupiterian/ML-Learning-Portfolio/blob/main/pytorch/PyTorch_Revision.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Import pytorch and subclasses
import torch
import torch.nn as nn
import torch.optim as optim
# Import numpy and pandas
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

In [ ]:
# Data Fetcher
import kagglehub
path = kagglehub.dataset_download("jayjoshi37/fifa-player-performance-and-market-value-analytics")
print("Path to dataset files:", path)

Using Colab cache for faster access to the 'fifa-player-performance-and-market-value-analytics' dataset.
Path to dataset files: /kaggle/input/fifa-player-performance-and-market-value-analytics

In [ ]:
# Load Data
df = pd.read_csv(f"{path}/fifa_player_performance_market_value.csv")
df.head()

,player_id,player_name,age,nationality,club,position,overall_rating,potential_rating,matches_played,goals,assists,minutes_played,market_value_million_eur,contract_years_left,injury_prone,transfer_risk_level
0,1,Player_1,23,Germany,Liverpool,ST,65,87,8,6,14,2976,122.51,3,No,Low
1,2,Player_2,36,England,FC Barcelona,ST,90,76,19,3,18,2609,88.47,5,No,High
2,3,Player_3,31,France,Juventus,RB,75,91,34,12,15,1158,20.24,3,No,Medium
3,4,Player_4,27,Portugal,Manchester City,LW,90,86,35,18,13,145,164.29,0,Yes,Medium
4,5,Player_5,24,Brazil,Liverpool,CDM,84,96,41,6,6,2226,121.34,4,No,Low

# Feature Extraction
Given that I have no experience or knowledge of NLP, I will be only using the numeric features from the dataset. The model will attempt to predict the ```overall_rating``` of a player given the ```age```, ```matches_played```, ```goals```, ```assists```, ```minutes_played```, ```market_Value_million_eur```, ```contract_years_left```, ```injury_prone```, and ```transfer_risk_level``` features.

<br/>

```injury_prone``` and ```transfer_risk_level``` will be mapped to numeric values with the following system:

```injury_prone```
*   No = 0
*   Yes = 1

```transfer_risk_level```
*   Low = 0
*   Medium = 1
*   High = 2

In [ ]:
# Feature modification
injury_map = {'No': 0, 'Yes': 1}
transfer_map = {'Low': 0, 'Medium': 1, "High": 2}

df["injury_prone"] = df["injury_prone"].replace(injury_map)
df["transfer_risk_level"] = df["transfer_risk_level"].replace(transfer_map)

df.head()

,player_id,player_name,age,nationality,club,position,overall_rating,potential_rating,matches_played,goals,assists,minutes_played,market_value_million_eur,contract_years_left,injury_prone,transfer_risk_level
0,1,Player_1,23,Germany,Liverpool,ST,65,87,8,6,14,2976,122.51,3,0,0
1,2,Player_2,36,England,FC Barcelona,ST,90,76,19,3,18,2609,88.47,5,0,2
2,3,Player_3,31,France,Juventus,RB,75,91,34,12,15,1158,20.24,3,0,1
3,4,Player_4,27,Portugal,Manchester City,LW,90,86,35,18,13,145,164.29,0,1,1
4,5,Player_5,24,Brazil,Liverpool,CDM,84,96,41,6,6,2226,121.34,4,0,0

In [ ]:
# Data Setup
X = df[["age", "matches_played", "goals", "assists", "minutes_played", "market_value_million_eur", "contract_years_left", "injury_prone", "transfer_risk_level"]]
y = df["overall_rating"]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [8]:
class Classifier(nn.Module):
  def __init__(self):
    super().__init__()
    self.layer1 = nn.Linear(in_features=9, out_features=18)
    self.layer2 = nn.ReLU()
    self.layer3 = nn.Linear(in_features=18, out_features=18)
    self.layer4 = nn.ReLU
    self.layer5 = nn.Linear(in_features=18, out_features=1)
  def forward(self, x):
    return (self.layer5(self.layer4(self.layer3(self.layer2(self.layer1(x))))))

model = Classifier()

In [ ]:
# Loss and Optimizer Functions

In [ ]:
## Training Loop
epochs = 101

for epoch in range(epochs):

  # 1. Training Mode
  model.train()

  # 2.